server:
  port: 14000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors: # 设置全局跨域处理
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters: # 设置全局熔断处理
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      routes: # 设置路由
        - id: userServer
          uri: lb://user-server
          predicates:
            - Path=/UserController/*/**

        - id: foodServer
          uri: lb://food-server
          predicates:
            - Path=/FoodController/*/**

        - id: businessServer
          uri: lb://business-server
          predicates:
            - Path=/BusinessController/*/**

        - id: cartServer
          uri: lb://cart-server
          predicates:
            - Path=/CartController/*/**
          metadata:
        	  # 读取超时
            response-timeout: 50000
            # 连接超时
            connect-timeout: 300000

        - id: ordersServer
          uri: lb://orders-server
          predicates:
            - Path=/OrdersController/*/**

        - id: deliveryaddressServer
          uri: lb://deliveryaddress-server
          predicates:
            - Path=/DeliveryAddressController/*/**

        - id: integrationServer
          uri: lb://integration-server
          predicates:
            - Path=/IntegrationController/*/**

        - id: configServer
          uri: lb://config-server
          predicates:
            - Path=/


eureka:
  client:
    service-url:
      #将自己注册给defaultZone所指定的eureka server集群上
      defaultZone: http://eurekaServer13000:13000/eureka/,http://eurekaServer13001:13001/eureka/
  instance:
    prefer-ip-address: true   #使用ip地址向eureka server进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #设置eureka控制台中显示的注册信息
    lease-renewal-interval-in-seconds: 5         #续约间隔时间
    lease-expiration-duration-in-seconds: 15     #续约到期时间