server:
  port: 15000
spring:
  application:
    name: config-server
  cloud:
    config: #有关springcloud config的配置
      server:
        git:
<<<<<<< HEAD
          uri: https://gitee.com/zljust/spring-cloud-server.git #git远程仓库地址
=======
          uri: https://gitee.com/zljust/elm.git #git远程仓库地址
>>>>>>> d4c2ac7e45d87adbaa7648556112dac62d60a623

# rabbitmq的配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
# 使用bus总线刷新配置文件
management:
    endpoints:
      web:
        exposure:
          include: bus-refresh #暴露bus-refresh节点，通过此节点刷新配置
#eureka配置
eureka:
  client:
    service-url:
      #将自己注册给defaultZone所指定的eureka server集群上
      defaultZone: http://eurekaServer13000:13000/eureka/,http://eurekaServer13001:13001/eureka/
  instance:
    prefer-ip-address: true   #使用ip地址向eureka server进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #设置eureka控制台中显示的注册信息
    lease-renewal-interval-in-seconds: 5         #续约间隔时间
    lease-expiration-duration-in-seconds: 15     #续约到期时间